// This file would typically be generated by a tool like Workbox (see Makefile)
// For a manual/placeholder setup:

const CACHE_NAME = 'servespeak-cache-v1';
const urlsToCache = [
  '/',
  '/index.html',
  '/manifest.json',
  // Vite assets will have hashed names; Workbox handles this automatically
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => {
        console.log('Opened cache');
        return cache.addAll(urlsToCache);
      })
  );
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request)
      .then(response => {
        // Cache hit - return response
        if (response) {
          return response;
        }
        // No cache hit - fetch from network
        return fetch(event.request);
      }
    )
  );
});
